version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
