/*
  Warnings:

  - You are about to drop the `books` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `users` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE `books`;

-- DropTable
DROP TABLE `users`;

-- CreateTable
CREATE TABLE `PERSON` (
    `ID` VARCHAR(191) NOT NULL,
    `FULL_NAME` VARCHAR(191) NOT NULL,
    `DOB` DATETIME(3) NOT NULL,
    `CONTACT` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `PERSON_CONTACT_key`(`CONTACT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREFERENCE` (
    `ID` VARCHAR(191) NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `PREFERENCE_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FOOD` (
    `ID` VARCHAR(191) NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `FOOD_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_PERSONToPREFERENCE` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_PERSONToPREFERENCE_AB_unique`(`A`, `B`),
    INDEX `_PERSONToPREFERENCE_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_FOODToPERSON` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_FOODToPERSON_AB_unique`(`A`, `B`),
    INDEX `_FOODToPERSON_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `_PERSONToPREFERENCE` ADD CONSTRAINT `_PERSONToPREFERENCE_A_fkey` FOREIGN KEY (`A`) REFERENCES `PERSON`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_PERSONToPREFERENCE` ADD CONSTRAINT `_PERSONToPREFERENCE_B_fkey` FOREIGN KEY (`B`) REFERENCES `PREFERENCE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_FOODToPERSON` ADD CONSTRAINT `_FOODToPERSON_A_fkey` FOREIGN KEY (`A`) REFERENCES `FOOD`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_FOODToPERSON` ADD CONSTRAINT `_FOODToPERSON_B_fkey` FOREIGN KEY (`B`) REFERENCES `PERSON`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
